<a href="https://colab.research.google.com/github/cRED-f/pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import  torch as t


In [3]:
## checking pytorch versionA
torch.__version__


'2.2.1+cu121'

In [5]:
# scalar tensor
scalar = t.tensor(5)

In [6]:
scalar

tensor(5)

In [7]:
scalar.ndim

0

In [8]:
scalar.item() ## Get the Python number within a tensor (only works with one-element tensors)

5

In [9]:
#vector
vector = t.tensor([5,2])

In [10]:
vector

tensor([5, 2])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
# matrix
MATRIX = t.tensor([[7,7],[4,6]])

In [15]:
MATRIX

tensor([[7, 7],
        [4, 6]])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
MATRIX.ndim

2

In [24]:
tn = t.tensor([[[7,7],[4,6],[2,6]]]) #calculate from reverse side(brackets)
tn.shape,tn.ndim

(torch.Size([1, 3, 2]), 3)

In [26]:
# create a random tensor of size (3,4)
rt= t.rand(size=(3,4))
rt.ndim,rt.shape,rt.dtype,rt

(2,
 torch.Size([3, 4]),
 torch.float32,
 tensor([[0.6540, 0.6144, 0.5318, 0.6975],
         [0.3493, 0.9505, 0.4911, 0.3615],
         [0.9617, 0.5648, 0.5693, 0.5784]]))

In [27]:
#zeros and ones
z= t.zeros(3,4)
o=t.ones(3,4)
z,o

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [28]:
# arange
tn= t.arange(start=0,end=10,step=1)
tn

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#create some tensors with specific datatypes using the dtype parameter.

In [33]:
float_32 = t.tensor([3.0,5.0,9.0],
                    dtype=t.float16,# defaults to None, which is torch.float32
                    device=None, # defaults to None, which uses the default tensor type
                    requires_grad=False #if true then operations are performed on the tensor are recorded
                    )

float_32,float_32.shape,float_32.ndim,float_32.dtype,float_32.device


(tensor([3., 5., 9.], dtype=torch.float16),
 torch.Size([3]),
 1,
 torch.float16,
 device(type='cpu'))

# manipulating tensor

In [36]:
tn= t.arange(1,4,1)

In [37]:
tn

tensor([1, 2, 3])

In [38]:
t.add(tn,10)

tensor([11, 12, 13])

In [39]:
tn1=t.rand(3,2)
tn2=t.rand(2,3)
t.matmul(tn1,tn2)

tensor([[0.3979, 0.4322, 0.5697],
        [0.7884, 0.7935, 1.1453],
        [0.6377, 0.7422, 0.9002]])

# shape error

In [40]:

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

t.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [44]:
# to fix this we can use transpose(switch the dimensions of a given tensor)

t.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#min, max, mean, sum

In [49]:
tn=t.arange(0,50,4)
tn


tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [54]:
print("min:",tn.min())
print("max:",tn.max())
#print("mean:",tn.mean()) # this will error
print("mean:",tn.type(t.float16).mean())#wont work without float datatype

min: tensor(0)
max: tensor(48)
mean: tensor(24., dtype=torch.float16)


# reshape( Add an extra dimension)

In [56]:
tn = t.arange(1,14,2)
tn,tn.shape

(tensor([ 1,  3,  5,  7,  9, 11, 13]), torch.Size([7]))

In [59]:
tnNshape=tn.reshape(1,7)
tnNshape,tnNshape.shape

(tensor([[ 1,  3,  5,  7,  9, 11, 13]]), torch.Size([1, 7]))

# Change view (keeps same data as original but changes view)


In [61]:
v= tn.view(1,7)
v.shape,v

(torch.Size([1, 7]), tensor([[ 1,  3,  5,  7,  9, 11, 13]]))