<a href="https://colab.research.google.com/github/cRED-f/deep-learning/blob/main/vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()

c = np.dot(a,b)

tac = time.time()

print(c)
print("Vectorized version:" + str(1000*(tac-tic)) + "ms")


c = 0
tic = time.time()
for i in range(1000000):
  c += a[i]*b[i]

tac = time.time()

print(c)
print("Non-vectorized version:" + str(1000*(tac-tic)) + "ms")

249908.91942078195
Vectorized version:1.8734931945800781ms
249908.91942077415
Non-vectorized version:500.40555000305176ms


In [6]:
a = np.random.randn(5,1)
a

array([[ 1.07263621],
       [-0.45320157],
       [ 0.03056235],
       [ 0.04815825],
       [ 0.69327824]])

In [7]:
a.T

array([[ 1.07263621, -0.45320157,  0.03056235,  0.04815825,  0.69327824]])

In [8]:
np.dot(a,a.T)

array([[ 1.15054845e+00, -4.86120417e-01,  3.27822871e-02,
         5.16562814e-02,  7.43635350e-01],
       [-4.86120417e-01,  2.05391664e-01, -1.38509066e-02,
        -2.18253939e-02, -3.14194789e-01],
       [ 3.27822871e-02, -1.38509066e-02,  9.34057450e-04,
         1.47182942e-03,  2.11882147e-02],
       [ 5.16562814e-02, -2.18253939e-02,  1.47182942e-03,
         2.31921691e-03,  3.33870660e-02],
       [ 7.43635350e-01, -3.14194789e-01,  2.11882147e-02,
         3.33870660e-02,  4.80634722e-01]])